apiVersion: v1
kind: ConfigMap
metadata:
  name: app-api-config
  namespace: demo-app-mba
data:
  POSTGRES_HOST: "postgresql-svc"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "mbaapi"
  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"
  DATABASE_URL: "postgresql+asyncpg://mbauser:mbapass@postgresql-svc:5432/mbaapi"
  REDIS_URL: "redis://redis-svc:6379/0"