apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-api-netpol
  namespace: demo-app-mba
spec:
  podSelector:
    matchLabels:
      app: app-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - namespaceSelector: {}
    - to:
        - podSelector: {}